### ISSUE TITLE
Does this also work on 1.12.2? I noticed it only says 1.12.1 but its new.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Wyn-Price/Noodle#1]
...

**Comment by Wyn-Price** [comment]
It should work. I can't promise anything tho

**Comment by P3rf3ctXZer0** [comment]
So you plan on supporting it. I will make sure to test it then.

**Comment by Wyn-Price** [comment]
I'm not going to directly change anything until 1.13 comes out. It should be able to work straight away, seeing as there's very little change. I'll change the curseforge page

**Comment by P3rf3ctXZer0** [comment]
In that case I will report bugs ;) for 1.12.2 if I encounter them.
