### ISSUE TITLE
ServerSide Crash - 1.12.2 forge 93

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Wyn-Price/Noodle#2]
https://gist.github.com/P3rf3ctXZer0/22608390b964038a64b3d90c11be2bbe

**Comment by Wyn-Price** [comment]
This is an import error I can fix in about 20 seconds. I'll do this when I get home from school today

**Comment by Wyn-Price** [comment]
@P3rf3ctXZer0  Ok new fixed version is released. If you want the world to be generated as a noodle , in server properties change `level-type=DEFAULT` to `level-type=NOODLE`. If you want custom noodles, copy the text from the customize section while creating a new Noodle world ( in single player), and paste after `generator-settings=`, in server properties
